---
name: install-linux

"on":
  push: {}

permissions:
  contents: read

jobs:
  install-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Reload Cache / pip
        uses: actions/setup-python@v4
        with:
          python-version: 3
          update-environment: false
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install package
        run: make install

      - name: Basic CLI Integration Tests
        run: |
          cr -d fetch
          cr -d rank -smg
