---
name: test

"on":
  push: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      PYTHON_SPOOF_VENV: /home/runner/work/chess_ratings/chess_ratings/.venv/bin/python

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Reload Cache / pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: PYTHON=${{ env.PYTHON_SPOOF_VENV }} make deps

      - name: Lint
        run: PYTHON=${{ env.PYTHON_SPOOF_VENV }} make lint

      - name: Test
        run: PYTHON=${{ env.PYTHON_SPOOF_VENV }} make test

      - name: Verify all python files are annotated at top
        run: make verify/py-annotated

      - name: Basic CLI Integration Tests
        run: |
          make install
          source .env
          cr rank -mg
